<a href="https://colab.research.google.com/github/19PA1A0225/AI-LAB/blob/master/EXPERIMENT_1_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1-Different ways to create Numpy arrays

In [ ]:
import numpy as np
a = np.array([1,2,3])
print (a)

[1 2 3]


In [ ]:
a = np.array([[4,5], [6,7]])
print (a)

[[4 5]
 [6 7]]


#2-Add,remove,modify elements in an array

###1-Numpy.arange

In [ ]:
import numpy as np
np.arange( 10, 50, 5 )

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

###2-numpy.reshape

In [ ]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

###3-ndarray.shape

In [ ]:
a.shape

(4, 5)

###4-ndarray.ndim

In [ ]:
a.ndim

2

###5-ndarray.dtype

In [ ]:
a.dtype

dtype('int64')

###6-ndarray.itemsize

In [ ]:
a.size

20

###7-type(ndarray)

In [ ]:
type(a)

numpy.ndarray

###3-Arithmetic operations on Numpy array

###1-Arithmetic operations on arrays apply elementwise.A new array is created and filled with the result

In [ ]:
a = np.array( [10,20,30,40] )
b = np.arange( 4 )
print(a)
print(b)
c = a-b
print(c)
print(b**2)
print(10*np.sin(a))
print(a<35)
a[0] +=10
print(a)

[10 20 30 40]
[0 1 2 3]
[10 19 28 37]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[ True  True  True False]
[20 20 30 40]


##2-Dot method


In [ ]:
A = np.array( [[3,3],[0,2]] )
B = np.array( [[3,0],[2,2]] )
print(A)
print(B)
print(A * B)
print(A @ B)
print(A.dot(B))
print(np.dot(A,B))

[[3 3]
 [0 2]]
[[3 0]
 [2 2]]
[[9 0]
 [0 4]]
[[15  6]
 [ 4  4]]
[[15  6]
 [ 4  4]]
[[15  6]
 [ 4  4]]


##3-Basic mathematical functions

In [ ]:
a=np.arange(4)
print(a)
b=np.random.random(4)
print(b)
print(np.add(a,b))
print(a + b)
print(a - b)
print(np.subtract(a, b))
print(a * b)
print(np.multiply(a, b))
print(a/b)
print(np.divide(a, b))

[0 1 2 3]
[0.03305505 0.47124831 0.71577164 0.3986514 ]
[0.03305505 1.47124831 2.71577164 3.3986514 ]
[0.03305505 1.47124831 2.71577164 3.3986514 ]
[-0.03305505  0.52875169  1.28422836  2.6013486 ]
[-0.03305505  0.52875169  1.28422836  2.6013486 ]
[0.         0.47124831 1.43154327 1.19595421]
[0.         0.47124831 1.43154327 1.19595421]
[0.         2.12202354 2.79418728 7.52537175]
[0.         2.12202354 2.79418728 7.52537175]


##4-Slicing and iterating of Numpy arrays

###1-Slicing-access list of elements

In [ ]:
a=np.arange(12)**3
print(a)
print(a[2])
print(a[2:3])
print(a[2:4])

[   0    1    8   27   64  125  216  343  512  729 1000 1331]
8
[8]
[ 8 27]


###slicing 2-D array

In [ ]:
a=np.arange(12).reshape(4,3)**2
print(a)
print(a[1:3])
print(a[1:3,1:2])
print(a[2,])
print(a[:2],)
print(a[:3,])
print(a[:3,:2])
print(a[:,2])


[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[[ 9 16 25]
 [36 49 64]]
[[16]
 [49]]
[36 49 64]
[[ 0  1  4]
 [ 9 16 25]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[ 0  1]
 [ 9 16]
 [36 49]]
[  4  25  64 121]


###2-Iterating

In [ ]:
a=np.arange(10).reshape(5,2)**2
print(a)
for i in a:
  print(i)
  

[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]]
[0 1]
[4 9]
[16 25]
[36 49]
[64 81]


In [ ]:
for i in a.flat:
  print(i)

0
1
4
9
16
25
36
49
64
81


##5-Matrix operations on Numpy arrays

###1-Difference between resize and reshape

In [ ]:
a=np.floor(10*np.random.random((3,4)))
a

array([[1., 6., 1., 4.],
       [8., 1., 2., 3.],
       [7., 9., 9., 1.]])

In [ ]:
a.reshape(2,6)

array([[1., 6., 1., 4., 8., 1.],
       [2., 3., 7., 9., 9., 1.]])

In [ ]:
a

array([[1., 6., 1., 4.],
       [8., 1., 2., 3.],
       [7., 9., 9., 1.]])

In [ ]:
a.resize(2,6)
a

array([[1., 6., 1., 4., 8., 1.],
       [2., 3., 7., 9., 9., 1.]])

###2-function transpose of matrix

In [ ]:
a.T

array([[1., 2.],
       [6., 3.],
       [1., 7.],
       [4., 9.],
       [8., 9.],
       [1., 1.]])